import { Header } from '@/shared/components';
import { Suspense } from 'react';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <main>{children}</main>;
}
